---
title: "Plot Sweep Expectation"
author: "Tom Booker"
date: "26/04/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


In this li'l workbook I'll make some plots of genetic diversity versus distance andto show how different combinations of selection 
```{r cars}
library(ggplot2)
```

## Read in the data


```{r pressure, echo=FALSE}

ns10 <- read.csv('Ns10_pa0.005.csv')
ns10$Ns <- 'Ns = 10 : pa = 0.005'

ns50 <- read.csv('Ns50_pa0.001.csv')
ns50$Ns <- 'Ns = 50 : pa = 0.001'

ns100 <- read.csv('Ns100_pa0.0005.csv')
ns100$Ns <- 'Ns = 100 : pa = 0.0005'

ns400 <- read.csv('Ns400_pa0.000125.csv')
ns400$Ns <- 'Ns = 400 : pa = 0.00125'

d<- rbind(ns10, ns50, ns100, ns400)
```

```{r plottingTrough}
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

ggplot(data = d, aes( x = distance, y = fitted, col = Ns))+
  geom_line(lwd = 0.9)+
  scale_x_continuous(limits=c(0,500))+
  scale_color_manual('', values = cbPalette)+
  ylab(expression(pi/pi[0]))+
  xlab(expression('Distance from element (4'* N[e]*'r)'))+
  theme_bw()

```


```{r plottingSFS}
n10<- read.csv('Ns10_pa_0.005.sfs.csv')
n10$Ns <- 'Ns = 10 : pa = 0.005'

n50<- read.csv('Ns50_pa_0.001.sfs.csv')
n50$Ns <- 'Ns = 50 : pa = 0.001'

n100<- read.csv('Ns100_pa_0.0005.sfs.csv')
n100$Ns <- 'Ns = 100 : pa = 0.0005'

n400<- read.csv('Ns400_pa_0.000125.sfs.csv')
n400$Ns <- 'Ns = 400 : pa = 0.00125'

str(data)
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
comb<-rbind(n10,n50, n100, n400)

ggplot(data = comb, aes( x = alleles, y = sfs, fill = Ns))+
  geom_bar(stat='identity', position = 'dodge')+
  scale_y_sqrt()+
  facet_grid(~Site.Class)+
  scale_fill_manual('', values = cbPalette)+
  scale_x_continuous(, breaks = seq(1,19))+
  ylab('Proportion of Sites')+
  xlab('# Derived Allele Copies')+
  theme_bw()

ggplot(data = comb, aes( x = alleles, y = sfs, fill = Ns))+
  geom_bar(stat='identity', position = 'dodge')+
  scale_y_sqrt()+
  facet_grid(Source ~ ., scales = 'free_y')+
  scale_fill_manual('', values = cbPalette)+
  scale_x_continuous(, breaks = seq(1,19))+
  ylab('Proportion of Sites')+
  xlab('# Derived Allele Copies')+
  theme_bw()

ggplot(data = comb[(comb$Site.Class != 'Synonymous') && (comb$alleles == 1) ,], aes(x = Ns, y = alpha, fill = Source))+
  geom_bar(stat = 'identity')

```
